variables:
  azureSubscription: 'AZR-RWD-PRD1'
  docker.imageName: 'eprcalculatorservice'
  acr.azureContainerRegistryName: 'prdrwdinfac1401'
  acr.repositoryName: 'eprcalculatorservicerepository'
  serviceName: 'PRDRWDWEBFA1411'          