variables:
- group: ServiceConnections
- name: azureSubscription
  value: $(ServiceConnectionPRD1)
- name: docker.imageName
  value: 'eprcalculatorservice'
- name: acr.azureContainerRegistryName
  value: 'prdrwdinfac1401'
- name: acr.repositoryName
  value: 'eprcalculatorservicerepository'
- name: serviceName
  value: 'PRDRWDWEBFA1411'